### ISSUE TITLE
Add analytics snippet

### ISSUE THREAD

**Issue by suninthesky** [nestauk/flow-temp-toolkit#1]
Replace this line https://github.com/nestauk/flow-temp-toolkit/blob/main/src/_includes/default.html#L53

**Comment by andy-mar** [comment]
I've replaced the above line with 


<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KMGTLRF');</script>


And additionally added the below directly below the body tag.


<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KMGTLRF"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by suninthesky** [comment]
Super. I've adjusted slightly as that led to nested <script> tags which isn't valid markup. 3a9abcb549a02ff546c58017b8ee0bae6f8a9fea
